[env]
platform = espressif32@6.12.0
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit GFX Library@^1.12.4
	RobTillaart/HX711@^0.6.3
	ESP32Async/AsyncTCP@^3.4.9
	ESP32Async/ESPAsyncWebServer@3.9.2
	bblanchon/ArduinoJson@^7.0.0
	h2zero/NimBLE-Arduino@2.3.7

[env:seeed_xiao_esp32c6]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-esp32-c6
platform_packages = platformio/tool-mklittlefs@^1.203.210628
extra_scripts = pre:scripts/setup_mklittlefs_path.py
build_flags = 
	${env.build_flags}
	-DBOARD_XIAO_ESP32C6
	
board_build.partitions = partitions.csv
