[env]
platform = espressif32@6.12.0
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps = 
    adafruit/Adafruit SSD1306@^2.5.15
    adafruit/Adafruit GFX Library@^1.12.4
    RobTillaart/HX711@^0.6.3
    ESP32Async/AsyncTCP@^3.4.9
    ESP32Async/ESPAsyncWebServer@3.9.2

[env:esp32s3-supermini]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv
build_flags = 
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_ESP32S3_SUPERMINI

[env:seeed_xiao_esp32c6]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-esp32-c6
build_flags = 
    ${env.build_flags}
    -DBOARD_XIAO_ESP32C6